### ISSUE TITLE
1.0.4 RELEASE seems to wasn't tagged

### ISSUE THREAD

**Issue by solomax** [Red5/red5-server-common#1]
1.0.4 RELEASE seems to wasn't tagged, so it is impossible to checkout/build it

**Comment by mondain** [comment]
I'll add it to my release checklist; my mistake. Is there a way to tag on a commit / push?

**Comment by solomax** [comment]
According to this guide: http://git-scm.com/book/en/v2/Git-Basics-Tagging
It should be simple :)

WBR, Maxim
(from mobile, sorry for the typos)

**Comment by mondain** [comment]
Ok I got it tagged and for my future reference:

```
# get hashes
git log --pretty=oneline
# tag on the hash
git tag -a [tag name] [commit hash id]
# push tag to remote
git push origin [tag name]
```
