### ISSUE TITLE
Audio Only Stream - ClassCastException (AudioData -> VideoData) in RTMPProtocolEncoder 

### ISSUE THREAD

**Issue by mkalamar** [Red5/red5-server-common#10]
I was streaming audio through red5 and occasionaly getting ClassCastException in RTMPProtocolEncoder in line 316 when it was trying to drop frames of video which didn't exist.

I added if( message instanceof VideoData) in line 316, and it solved the problem. But maybe you want to look into the process of dropping frames if the stream is only audio.

```
            if (isDroppable) {

                if(message instanceof VideoData) {

                    VideoData video = (VideoData) message;
```

Red 5 is realy great! Thank you all for doing so good job :)

Best Regards,
Marta Kalamar

**Comment by ritzalam** [comment]
Saw this too. Was about to send a PR. Thanks for fixing.
