### ISSUE TITLE
Incorrect usage of ScheduledExecutorService in org.red5.server.stream.consumer.FileConsumer

### ISSUE THREAD

**Issue by mayras** [Red5/red5-server-common#20]
Hello,
Creation 'scheduledExecutorService' is on line 180:

scheduledExecutorService = Executors.newScheduledThreadPool(schedulerThreadSize, new CustomizableThreadFactory("FileConsumerExecutor-"));

There is no shutdown for this service. 
Solution: make FileConsumer extends AutoCloseable and shutdown service in close method.

Also whole architecture of this FileConsumer isn't right, there should be some solution for Java IO Streaming to save data, not only to file.

**Comment by mondain** [comment]
I'm not familiar with AutoCloseable, do you have an example? Also without a code link, version, or commit id the line number leaves us to assume current head at the time of submission of this issue. 
As for your last line, we accept submissions / pull requests if you've got a good idea or fix.

**Comment by mayras** [comment]
Just google it, you are maintainers of red5 and it's very strange that you don't know basic API of Java in face of AutoCloseable. Idea is just to shutdown service via variable 'scheduledExecutorService' in some way which you know as supporter.

**Comment by mondain** [comment]
Being adversarial or highly critical of this team or the project itself will not help you nor the project. If you have an issue, offer a solution, if you have nothing constructive to add, then be silent.

**Comment by mondain** [comment]
Fixed in the next commit by using Spring beans for start/stop.
