### ISSUE TITLE
RTMPConnection.getLastPingTime()  always return -1

### ISSUE THREAD

**Issue by wicm** [Red5/red5-server-common#51]
Hello, I have updated my red server from the version 1.0.2 to 1.0.8. 
After the update the RTMPConnection.getLastPingTime()  function returns always -1.

i update my red5 server from 1.0.2 to 1.0.8 and i notice that the function RTMPConnection.getLastPingTime()  always return -1.
[RTMPConnection.patch.txt](https://github.com/Red5/red5-server-common/files/674323/RTMPConnection.patch.txt)

**Comment by mondain** [comment]
Patch applied to 1.0.9-SNAPSHOT
