### ISSUE TITLE
broken video live stream 

### ISSUE THREAD

**Issue by wicm** [Red5/red5-server-common#54]
Use this test application http://www.wowza.com/resources/4.4.1/examples/VideoChat/FlashRTMPPlayer/player.html together with the live demo (rtmp://localhost/live), so the playback of the videostream is incorrect.
If I understood the function of the video buffer correctly, so it must be switched to unbuffered stream at the next key frame.
I used the following patch with version 1.0.8.

[switch_to_unbufferd_stream.txt](https://github.com/Red5/red5-server-common/files/752669/switch_to_unbufferd_stream.txt)

**Comment by mondain** [comment]
Thanks @wicm I've applied your patch, it will be in the next push.
