### ISSUE TITLE
Ping Request not sent with Full header

### ISSUE THREAD

**Issue by GoelBiju** [Red5/red5-server-common#63]
I had noticed that whilst receiving data from a sample Red5 server, the ping request event from the server had been sent with the header type as continuation. This meant that it contained no data-type/timestamp or body length.

I am not sure if this is the case with all versions but is the ping request is supposed to be sent with full header type instead?

Thanks 😃

**Comment by mondain** [comment]
There are several types for Ping / control messages in Red5, continuation is only one of them.

**Comment by GoelBiju** [comment]
@mondain , I wasn't sure if this ping message was specific to Red5 servers or not as all other Rtmp servers seem to use full headers when sending a ping message. The data type field is at least needed as a client cannot parse the ping message without it if it was sent with a continuation header.

**Comment by mondain** [comment]
Here is the Ping source; it should still be to-spec https://github.com/Red5/red5-server-common/blob/b8049c826c854403b7fb072d8ba84f60485cb771/src/main/java/org/red5/server/net/rtmp/event/Ping.java Also I suggest you read through the RTMP spec to ensure we are on the same page http://wwwimages.adobe.com/www.adobe.com/content/dam/acom/en/devnet/rtmp/pdf/rtmp_specification_1.0.pdf

**Comment by GoelBiju** [comment]
@mondain it may be possible that it just wasn't being used properly in a specific instance. It is alright, I appreciate your help.
