### ISSUE TITLE
Maven build issue (jaudiotagger)

### ISSUE THREAD

**Issue by vbence** [Red5/red5-server-common#9]
_I remember seeing a similar report in one of the subprojects, but could not find it now. Since this is the package I,m trying to build I will post my workaround here._

Compiling will fail because maven can not find the following dependency:

```
jaudiotagger-2.0.4-SNAPSHOT.pom
```

After googleing for it and finding a repository (grails.org's) I added it to the project's POM:

```
        <repository>
            <id>grails</id>
            <name>Grails</name>
            <url>http://repo.grails.org/grails/repo/</url>
        </repository> 
```

Again, this is a **workaround** if you want to compile the project, until the good people at Red5 fix the dependency issue.

**Comment by maritelle** [comment]
I have the same problem

**Comment by mondain** [comment]
We regressed back to an older version and this is resolved.
